---
title: "associations"
author: "Jieqi Tu (jt3098)"
date: "12/27/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

### Import dataset
```{r import dataset}
# Import dataset
CL = readxl::read_excel("./ABC_Cord Blood_Metabolomics_CL data_14Nov2019.xlsx") %>% janitor::clean_names()
BA = readxl::read_excel("./ABC_Cord Blood_Metabolomics_BA data_14Nov2019.xlsx") %>% janitor::clean_names()
PM = readxl::read_excel("./ABC_Cord Blood_Metabolomics_PM data_14Nov2019.xlsx") %>% janitor::clean_names()
```


### Convert 0 to half of the minimum values
```{r}
CL_data = CL[11:491]
BA_data = BA[11:266]
PM_data = PM[11:193]
CL_data[CL_data == 0] = NA
BA_data[BA_data == 0] = NA
PM_data[PM_data == 0] = NA
CL_min = sapply(CL_data[1:481], function(x) min(x, na.rm = T))
BA_min = sapply(BA_data[1:256], function(x) min(x, na.rm = T))
PM_min = sapply(PM_data[1:183], function(x) min(x, na.rm = T))
CL_data = CL[11:491]
BA_data = BA[11:266]
PM_data = PM[11:193]
# Convert 0 to half of the minimum value
for(i in 1:481) {
  CL_data[i][CL_data[i]==0] = 0.5*CL_min[i]
}

for(i in 1:256) {
  BA_data[i][BA_data[i]==0] = 0.5*BA_min[i]
}

for(i in 1:183) {
  PM_data[i][PM_data[i]==0] = 0.5*PM_min[i]
}

CL_info = CL[1:10]
CL_new = cbind.data.frame(CL_info, CL_data)

BA_info = BA[1:10]
BA_new = cbind.data.frame(BA_info, BA_data)

PM_info = PM[1:10]
PM_new = cbind.data.frame(PM_info, PM_data)
```

### Delete outliers
```{r outliers}
# Delete outliers that identified by PCA
CL_new = CL_new[-c(55, 56, 121, 122, 195, 196),]
BA_new = BA_new[-c(5,6,41, 42, 191, 192, 121, 122, 125, 126, 195, 196),]
PM_new = PM_new
```

### Scaling
```{r scale data}
# Calculate the standard deviation of the control group for each dataset
BA_c = BA_new %>% 
  group_by(strata) %>% 
  filter(asd == 0)
CL_c = CL_new %>% 
  group_by(strata) %>% 
  filter(asd == 0)
PM_c = PM %>% 
  group_by(strata) %>% 
  filter(asd == 0)
sd_BA = sapply(BA_c[11:266], function(x) sd(x))
sd_CL = sapply(CL_c[11:491], function(x) sd(x))
sd_PM = sapply(PM_c[11:193], function(x) sd(x))

# Divide the standard deviation
for(i in 1:256) {
  BA_new[i+10] = BA_new[i+10]/sd_BA[i]
}
for(i in 1:481) {
  CL_new[i+10] = CL_new[i+10]/sd_CL[i]
}
for(i in 1:183) {
  PM_new[i+10] = PM_new[i+10]/sd_PM[i]
}
```

### Log transformation
```{r log transformation}
# base 10 log transformation
BA_log = BA_new
CL_log = CL_new
PM_log = PM_new
for(i in 1:256) {
  BA_log[i+10] = log10(BA_new[i+10])
}

for(i in 1:481) {
  CL_log[i+10] = log10(CL_new[i+10])
}

for(i in 1:183) {
  PM_log[i+10] = log10(PM_new[i+10])
}

```

### Recode birth year
```{r recode birth year}
CL_log = 
  CL_log %>% 
  mutate(year_new = ifelse(birth_year <= 2000, "before 2000", birth_year))

PM_log = 
  PM_log %>% 
  mutate(year_new = ifelse(birth_year <= 2000, "before 2000", birth_year))

BA_log = 
  BA_log %>% 
  mutate(year_new = ifelse(birth_year <= 2000, "before 2000", birth_year))
```

### Test for associations using conditional logistic regression
```{r CL association}
# CL data associations
library(survival)
column_name = colnames(CL_log)
predictor_name = column_name[11:491]
store = data.frame(matrix(ncol = 7, nrow = 0))
colnames(store) = c("term", "estimate", "std.error", "statistic", "p.value",   "conf.low",  "conf.high")
for(i in 1:481) {
  data = CL_log[i+10]
  a = unlist(data)
  model = clogit(asd~birth_season + as.factor(year_new) + sex_ab_cpairsampleselection1 + a, data = CL_log)
  result = broom::tidy(model)
  store[i, ] = result[11,]
}

CL_result = 
  store %>% 
  mutate(term = predictor_name)
```

```{r BA association}
# BA data associations
column_name = colnames(BA_log)
predictor_name = column_name[11:266]

store_BA = data.frame(matrix(ncol = 7, nrow = 0))
colnames(store_BA) = c("term", "estimate", "std.error", "statistic", "p.value",   "conf.low",  "conf.high")
for(i in 1:256) {
  data = BA_log[i+10]
  a = unlist(data)
  model = clogit(asd~birth_season + as.factor(year_new) + sex_ab_cpairsampleselection1 + a, data = BA_log)
  result = broom::tidy(model)
  store_BA[i, ] = result[10,]
}
BA_result = 
  store_BA %>% 
  mutate(term = predictor_name)
```

```{r PM association}
# PM data associations
column_name = colnames(PM_log)
predictor_name = column_name[11:193]

store_PM = data.frame(matrix(ncol = 7, nrow = 0))
colnames(store_PM) = c("term", "estimate", "std.error", "statistic", "p.value",   "conf.low",  "conf.high")
for(i in 1:183) {
  data = PM_log[i+10]
  a = unlist(data)
  model = clogit(asd~birth_season + as.factor(year_new) + sex_ab_cpairsampleselection1 + a, data = PM_log)
  result = broom::tidy(model)
  store_PM[i, ] = result[11,]
}

PM_result = 
  store_PM %>% 
  mutate(term = predictor_name)
```

### False Discovery Rate Correction
```{r FDR}
# Calculate the adjusted p-values
# CL data
CL_result$adjusted_pval = p.adjust(p = CL_result$p.value, method = "BH")

# PM data
PM_result$adjusted_pval = p.adjust(p = PM_result$p.value, method = "BH")

# BA data
BA_result$adjusted_pval = p.adjust(p = BA_result$p.value, method = "BH")
```

