---
title: "Machine Learning Methods"
author: "Jieqi Tu (jt3098)"
date: "2/19/2020"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(glmnet)
library(pROC)
```

## Import dataset
```{r import dataset}
# Import dataset
CL = readxl::read_excel("./data_new/ABC_Cord Blood_Metabolomics_CL data_15Jan2020.xlsx") 
BA = readxl::read_excel("./data_new/ABC_Cord Blood_Metabolomics_BA data_15Jan2020.xlsx") 
PM = readxl::read_excel("./data_new/ABC_Cord Blood_Metabolomics_PM data_15Jan2020.xlsx") 
OL =  readxl::read_excel("./data_new/ABC_Cord Blood_Metabolomics_OL data_15Jan2020.xlsx")
```


## Convert 0 to half of the minimum values
```{r convert 0 to half of the minimum values}
CL_data = CL[11:491]
BA_data = BA[11:266]
PM_data = PM[11:193]
OL_data = OL[11:81]
CL_data[CL_data == 0] = NA
BA_data[BA_data == 0] = NA
PM_data[PM_data == 0] = NA
OL_data[OL_data == 0] = NA
CL_min = sapply(CL_data[1:481], function(x) min(x, na.rm = T))
BA_min = sapply(BA_data[1:256], function(x) min(x, na.rm = T))
PM_min = sapply(PM_data[1:183], function(x) min(x, na.rm = T))
OL_min = sapply(OL_data[1:71], function(x) min(x, na.rm = T))

CL_data = CL[11:491]
BA_data = BA[11:266]
PM_data = PM[11:193]
OL_data = OL[11:81]
# Convert 0 to half of the minimum value
for(i in 1:481) {
  CL_data[i][CL_data[i]==0] = 0.5*CL_min[i]
}

for(i in 1:256) {
  BA_data[i][BA_data[i]==0] = 0.5*BA_min[i]
}

for(i in 1:183) {
  PM_data[i][PM_data[i]==0] = 0.5*PM_min[i]
}

for(i in 1:71) {
  OL_data[i][OL_data[i]==0] = 0.5*OL_min[i]
}

CL_info = CL[1:10]
CL_new = cbind.data.frame(CL_info, CL_data)

BA_info = BA[1:10]
BA_new = cbind.data.frame(BA_info, BA_data)

PM_info = PM[1:10]
PM_new = cbind.data.frame(PM_info, PM_data)

OL_info = OL[1:10]
OL_new = cbind.data.frame(OL_info, OL_data)
```

## Delete outliers
```{r outliers}
# Delete outliers identified in PCA
CL_new = CL_new[-c(39, 40, 55, 56, 121, 122, 199, 200),]
BA_new = BA_new[-c(5,6,41, 42, 191, 192, 121, 122, 125, 126, 195, 196, 199, 200),]
PM_new = PM_new[-c(31, 32),]
OL_new = OL_new[-c(159, 160, 123, 124, 29, 30, 85, 86),]
```

## Scaling and Transformation
```{r scaling and transformation}
# Base 10 log transformation
BA_log = BA_new
CL_log = CL_new
PM_log = PM_new
OL_log = OL_new
for(i in 1:256) {
  BA_log[i+10] = log10(BA_new[i+10])
}

for(i in 1:481) {
  CL_log[i+10] = log10(CL_new[i+10])
}

for(i in 1:183) {
  PM_log[i+10] = log10(PM_new[i+10])
}

for(i in 1:71) {
  OL_log[i+10] = log10(OL_new[i+10])
}
# Divide variables by the sd of control groups
BA_c = BA_log %>% 
  group_by(Strata) %>% 
  filter(PROT_ASD_2015 == 0)
CL_c = CL_log %>% 
  group_by(Strata) %>% 
  filter(PROT_ASD_2015 == 0)
PM_c = PM_log %>% 
  group_by(Strata) %>% 
  filter(PROT_ASD_2015 == 0)
OL_c = OL_log %>% 
  group_by(Strata) %>% 
  filter(PROT_ASD_2015 == 0)
sd_BA = sapply(BA_c[11:266], function(x) sd(x))
sd_CL = sapply(CL_c[11:491], function(x) sd(x))
sd_PM = sapply(PM_c[11:193], function(x) sd(x))
sd_OL = sapply(OL_c[11:81], function(x) sd(x))

# Divide the standard deviation
for(i in 1:256) {
  BA_log[i+10] = BA_log[i+10]/sd_BA[i]
}
for(i in 1:481) {
  CL_log[i+10] = CL_log[i+10]/sd_CL[i]
}
for(i in 1:183) {
  PM_log[i+10] = PM_log[i+10]/sd_PM[i]
}
for(i in 1:71) {
  OL_log[i+10] = OL_log[i+10]/sd_OL[i]
}
```

## Classification Methods
### Initial Setting
```{r set control}
# Initial setting for machine learning methods
ctrl = trainControl(method = "repeatedcv", number = 5,
                    summaryFunction = twoClassSummary,
                    classProbs = TRUE)
```

### Linear Methods for Classification

#### Logistic Regression
```{r logistic regression, warning=FALSE}
# Delete matching variables
CL_analysis = CL_log[,-c(1, 2, 3, 4, 5, 6, 7, 8, 10)] 

# Divide data into two parts
set.seed(1029)
rowTrain = createDataPartition(y = CL_analysis$PROT_ASD_2015,
                               p = 0.8,
                               list = FALSE)

# Rename the outcome variable
CL_analysis$PROT_ASD_2015 = ifelse(CL_analysis$PROT_ASD_2015 == "1", "Positive", "Negative")

# Rename the outcome variable
model.glm = train(x = CL_analysis[rowTrain, 2:482],
                  y = CL_analysis$PROT_ASD_2015[rowTrain],
                  method = "glm",
                  metric = "ROC",
                  trControl = ctrl)

# Test performance
glm.pred = predict(model.glm, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.glm = roc(CL_analysis$PROT_ASD_2015[-rowTrain], glm.pred)
plot(roc.glm, legacy.axes = T)
```

#### LASSO

```{r LASSO for CL data}
# Lasso regression
set.seed(1029)
CL_analysis$PROT_ASD_2015 = as.factor(CL_analysis$PROT_ASD_2015)
# Set outcome and features
x_CL = model.matrix(CL_analysis$PROT_ASD_2015~., CL_analysis)[rowTrain, -1]
y_CL = CL_analysis$PROT_ASD_2015[rowTrain]
# Fit LASSO Regression
model.lasso = train(x = CL_analysis[rowTrain, 2:482],
                    y = CL_analysis$PROT_ASD_2015[rowTrain],
                    method = "glmnet",
                    tuneGrid = expand.grid(alpha = 1,
                                           lambda = exp(seq(-5, -1, length = 1000))),
                    metric = "ROC",
                    family = "binomial",
                    trControl = ctrl)
plot(model.lasso, xTrans = function(x) log(x))
model.lasso$bestTune
coef(model.lasso$finalModel, model.lasso$bestTune$lambda)
lasso.pred = predict(model.lasso, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.lasso = roc(CL_analysis$PROT_ASD_2015[-rowTrain], lasso.pred)
plot(roc.lasso, legacy.axes = T)
```

### Classification Trees

#### Random Forest
```{r RF for CL data}
# Random Forest
rf.grid = expand.grid(mtry = 1:160,
                      splitrule = "gini",
                      min.node.size = 1:6)

set.seed(1029)

model.rf = train(PROT_ASD_2015~., CL_analysis,
                 subset = rowTrain,
                 method = "ranger",
                 tuneGrid = rf.grid,
                 metric = "ROC",
                 trControl = ctrl)
```

#### AdaBoost
```{r AdaBoost for CL data}
# Adaboost loss function
ada.grid = expand.grid(n.trees = c(1000, 2000, 3000),
                       interaction.depth = 1:6,
                       shrinkage = c(0.001, 0.003, 0.005),
                       n.minobsinnode = 1)

set.seed(1029)

model.ada = train(PROT_ASD_2015~., CL_analysis,
                  subset = rowTrain,
                  tuneGrid = ada.grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)

```

#### XGBoost
```{r XGboost for CL data}
# XGBoost
xgboost.grid = expand.grid(eta = 0.1, 
                           colsample_bytree=c(0.5,0.7),
                           max_depth=c(3,6),
                           nrounds=100,
                           gamma=1,
                           min_child_weight=2,
                           subsample = 1)

set.seed(1029)

modelxgboost = train(PROT_ASD_2015~., 
                     CL_analysis,
                     subset = rowTrain,
                     method = "xgbTree",
                     trControl = ctrl,
                     tuneGrid = xgboost.grid,
                     metric = "ROC",
                     verbose = F)
```

### Model Comparison
```{r compare ROC curves}
# Calculate ROC for each model
glm.pred = predict(model.glm, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.glm = roc(CL_analysis$PROT_ASD_2015[-rowTrain], glm.pred)

lasso.pred = predict(model.lasso, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.lasso = roc(CL_analysis$PROT_ASD_2015[-rowTrain], lasso.pred)

ada.pred = predict(model.ada, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.ada = roc(CL_analysis$PROT_ASD_2015[-rowTrain], ada.pred)

rf.pred = predict(model.rf, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.rf = roc(CL_analysis$PROT_ASD_2015[-rowTrain], rf.pred)

xgboost.pred = predict(modelxgboost, newdata = CL_analysis[-rowTrain,], type = "prob")[,2]
roc.xgboost = roc(CL_analysis$PROT_ASD_2015[-rowTrain], xgboost.pred)

auc = c(roc.glm$auc[1],roc.lasso$auc[1],roc.ada$auc[1],roc.rf$auc[1],roc.xgboost$auc[1])

plot(roc.glm, legacy.axes = T)
plot(roc.lasso, col = 2, add = T)
plot(roc.ada, col= 3, add = T)
plot(roc.rf, col= 4, add = T)
plot(roc.xgboost, col= 5, add = T)
modelNames = c("glm", "lasso", "AdaBoost", "random forest", "XGBoost")
legend("bottomright", legend = paste0(modelNames, ": ", round(auc, 3)), col = 1:5, lwd = 2)

res = resamples(list(GLM = model.glm,
                     LASSO = model.lasso,
                     AdaBoost = model.ada,
                     RandomForest = model.rf,
                     XGBoost =modelxgboost))

summary(res)

bwplot(res, metric = "ROC")
```

