---
title: "PCA analysis"
author: "Jieqi Tu, jt3098"
date: "11/16/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r Import data}
# Import datasets
ABC_total_raw = readxl::read_excel("./ABC_Cord Blood_Metabolomics_new.xlsx") %>% as.data.frame()

# Tidy dataset
ABC_total = 
  ABC_total_raw %>% 
  janitor::clean_names()

# Divide the dataset to confounding information and experimental data
ABC_information = ABC_total[1:10]
ABC_data = ABC_total[11:930]
```

```{r principal component analysis}
# Generate z-scores for each analyte
# Extract the subset of all controls
subset_control = 
  ABC_total %>% 
  group_by(strata) %>% 
  filter(asd == 0)

# Calculate the mean and standard deviation of the control group
mean_control = sapply(subset_control[11:930], function(x) mean(x)) 
sd_control = sapply(subset_control[11:930], function(x) sd(x))

# Write a for-loop to calculate z-score of data for both control and ASD groups
for(i in 1:920) {
  ABC_data[i] = (ABC_data[i] - mean_control[i])/sd_control[i]
}
# Principal component analysis
ABC_pca = prcomp(ABC_data[c(1:920)], center = T, scale. = T)
summary(ABC_pca)

# Plot PC1 and PC2
library(ggfortify)
autoplot(ABC_pca, label = T, label.size = 3)
```

```{r delete outliers and fit another PCA}
# Delete outliers 
ABC_total = 
  ABC_total[-c(55, 56, 121, 122, 195, 196), ]

# Re-generate z-scores
subset_control = 
  ABC_total %>% 
  group_by(strata) %>% 
  filter(asd == 0)

# Calculate the mean and standard deviation of the control group
mean_control = sapply(subset_control[11:930], function(x) mean(x)) 
sd_control = sapply(subset_control[11:930], function(x) sd(x))

ABC_data_2 = ABC_total[11:930]
# Write a for-loop to calculate z-score of data for both control and ASD groups
for(i in 1:920) {
  ABC_data_2[i] = (ABC_data_2[i] - mean_control[i])/sd_control[i]
}

# PCA again
ABC_pca_2 = prcomp(ABC_data_2[c(1:920)], center = T, scale. = T)
summary(ABC_pca_2)

# Plot PC1/PC2
autoplot(ABC_pca_2, label = T, label.size = 3)

# Plot PC2/PC3
autoplot(ABC_pca_2, x=2, y=3, label = T, label.size = 3)
```

